// automatically generated by the FlatBuffers compiler, do not modify

package echo

const (
	EffectPing = 0
	EffectPong = 1
)

var EnumNamesEffect = map[int]string{
	EffectPing:"Ping",
	EffectPong:"Pong",
}

