// automatically generated by the FlatBuffers compiler, do not modify

package echo

const (
	TypeUndefined = 0
	TypeBoolean = 1
	TypeString = 2
)

var EnumNamesType = map[int]string{
	TypeUndefined:"Undefined",
	TypeBoolean:"Boolean",
	TypeString:"String",
}

